[package]
name = "xmlparser"
# When updating version, also modify html_root_url in the lib.rs and in the README
version = "0.4.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["xml", "parser", "tokenizer"]
categories = ["parsing"]
license = "MIT/Apache-2.0"
description = "Pull-based, zero-allocation XML parser."
repository = "https://github.com/RazrFalcon/xmlparser"
documentation = "https://docs.rs/xmlparser/"
readme = "README.md"

[dependencies]
log = "0.4"
failure = "0.1.1"

[dev-dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rustc-test = "0.3"
stderrlog = "0.3"

[lib]
path = "src/lib.rs" # for cargo-readme
doctest = true
