[package]
name = "xmlparser"
# When updating version, also modify html_root_url in the lib.rs and in the README
version = "0.4.1"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["xml", "parser", "tokenizer"]
categories = ["parsing"]
license = "MIT/Apache-2.0"
description = "Pull-based, zero-allocation XML parser."
repository = "https://github.com/RazrFalcon/xmlparser"
documentation = "https://docs.rs/xmlparser/"
readme = "README.md"

[lib]
path = "src/lib.rs" # for cargo-readme
doctest = true
